# -*- coding: utf-8 -*-
"""Lab1_Numpy,Pandas,Tensorflow,TienXuLyDuLieu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jp4xxyHi1u2IrSPBRX1feU4MXVpxyf0v
"""

!pip install numpy

import numpy as np
#my_list=[1,9,15,39]
#print('Python list:',my_list)
#my_numpy_array=np.array(my_list)
#print('Numpy array:',my_numpy_array)

a=np.array([1,9,15,39])
print(a)

import numpy as np
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c.dtype)

import numpy as np
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(d)
print(d.shape)
print(d.dtype)

import numpy as np
e=np.zeros((2,2))
f=np.ones((3,3))
print('Zero matrix:\n',e)
print('One matrix\n',f)

import numpy as np
e=np.array([[1,2,3],[4,5,6]])
print(e)
print(e.shape)
f=e.reshape(3,2)
print(f)
g=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(g)
print(g.shape)
h=g.reshape(3,4)
print('reshape (3,4)\n',h)
j=g.reshape(3,2,2)
print('reshape (3,2,2)\n',j)
k=g.reshape(2,3,2)
print('reshape (2,3,2)\n',k)

import numpy as np
e=np.array([[1,2,3],[4,5,6]])
f=e.flatten()
print(f)
g=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
j=g.flatten()
print(j)

f=np.array([1,2,3])
g=np.array([4,5,6])
h_stack=np.hstack((f,g))
print(h_stack)
v_stack=np.vstack((f,g))
print(v_stack)

import numpy as np
a=np.random.randint(100,size=(5,))
print('Random 1-D array\n',a)
b=np.random.randint(100,size=(3,4))
print('Random 2-D array\n',b)
c=np.random.randint(100,size=(3,4,3))
print('Random 3-D array\n',c)

import numpy as np
a=np.random.rand(5)
print('Random 1-D array\n',a)
b=np.random.rand(3,4)
print('Random 2-D array\n',b)
c=np.random.rand(3,4,3)
print('Random 3-D array\n',c)

import numpy as np
a=np.random.normal(5,0.5,10)
print(a)

import numpy as np
a=np.random.choice([2,4,6,8,10,12,14,16,18,20])
print(a)
b=np.random.choice([2,4,6,8,10,12,14,16,18,20],size=(3,5))
print(b)

import numpy as np
A=np.matrix(np.ones((5,5)))
print(A)
np.array(A)[2]=2
print('Change values of third row with array\n',A)
np.asarray(A)[2]=2
print('Chang values of third row with asarray\n',A)

import numpy as np
a=np.arange(1,20)
print(a)
b=np.arange(1,20,2)
print(b)

import numpy as np
a=np.linspace(1,5,num=10)
print(a)

import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
print('first row:',a[0])
print('second row:',a[1])
print('second column:',a[:,1])
print('first column:',a[:,0])
print('first element of first row:',a[1,:2])

!pip install pandas

import pandas as pd
a=pd.Series([1,2,3])
print(a)
print('First value:',a[0])
b=pd.Series([1,2,3],index=['a','b','c'])
print(b)
print('First value:',b['a'])
calories={"day1":420,"day2":380,"day3":390}
myvar=pd.Series(calories)
print(myvar)

import pandas as pd
h=np.array([[1,2],[3,4]])
df_h=pd.DataFrame(h)
print('DataFrame:\n',df_h)
numpy_h=np.array(df_h)
print('Numpy array:\n',numpy_h)

import pandas as pd
dic = {'Name':['John','Smith'],'Age':[30,40]}
df_dic=pd.DataFrame(dic)
print(df_dic)

import pandas as pd
r=np.random.randn(20,4)
df=pd.DataFrame(r,columns=['so1','so2','so3','so4'])
print(df.head())

import pandas as pd
r=np.random.randn(20,4)
df=pd.DataFrame(r,columns=['so1','so2','so3','so4'])
print(df.head())
print('Chon cot so1\n',df['so1'])
print('Chon nhieu dong\n',df[0:3])
print('Chon nhieu cot\n',df[['so1','so3']])
print('Chon nhieu dong, nhieu cot\n',df.iloc[:3,:2])
df=df.drop(columns=['so1','so4'])
print(df)

import pandas as pd
df1=pd.DataFrame({'Name':['John','Smith','Paul'],'Age':[25,30,50]},index=[0,1,2])
df2=pd.DataFrame({'Name':['Adam','Smith'],'Age':[26,11]},index=[3,4])
df_concat=pd.concat([df1,df2])
print(df_concat)
print('Drop duplicatevalues in DataFrame\n',df_concat.drop_duplicates('Name'))
print('Sort values in DataFrame\n',df_concat.sort_values('Age'))
df_rename=df_concat.rename(columns={'Name':'Surname','Age':'Age_pupil'})
print('Rename columns of DataFrame\n',df_rename)

import numpy as np
import pandas as pd

def thuc_thi_bai_tap(so_bai):
    if so_bai == 1:
        print("\n[Bai 1] Kiem tra tat ca phan tu khac 0")
        mang = np.random.randint(0, 21, size=(3, 3))
        print("Mang:\n", mang)
        print("Tat ca khac 0:", np.all(mang != 0))

    elif so_bai == 2:
        print("\n[Bai 2] Kiem tra ton tai it nhat mot phan tu khac 0")
        mang = np.random.randint(0, 21, size=(3, 3))
        print("Mang:\n", mang)
        print("Ton tai phan tu khac 0:", np.any(mang != 0))

    elif so_bai == 3:
        print("\n[Bai 3] So sanh hai mang")
        m1, m2 = np.array([1, 5]), np.array([2, 4])
        print(f"m1: {m1}, m2: {m2}")
        print("Lon hon:", np.greater(m1, m2))
        print("Nho hon hoac bang:", np.less_equal(m1, m2))

    elif so_bai == 4:
        print("\n[Bai 4] Tao mang 10 so 1, 10 so 0, 10 so 5")
        kq = np.concatenate([np.ones(10), np.zeros(10), np.full(10, 5)])
        print(kq)

    elif so_bai == 5:
        print("\n[Bai 5] Mang so chan trong khoang [30, 70]")
        print(np.arange(30, 71, 2))

    elif so_bai == 6:
        print("\n[Bai 6] Ma tran don vi 3x3")
        print(np.identity(3))

    elif so_bai == 7:
        print("\n[Bai 7] Mang 10 phan tu [15, 55], loai dau va cuoi")
        mang = np.linspace(15, 55, 10)
        print("Goc:", mang)
        print("Ket qua:", mang[1:-1])

    elif so_bai == 8:
        print("\n[Bai 8] Dao dau cac so tu 9 den 15")
        mang = np.arange(21)
        mang[(mang >= 9) & (mang <= 15)] *= -1
        print(mang)

    elif so_bai == 9:
        print("\n[Bai 9] Ma tran 3x4 gia tri tu 10 den 21")
        print(np.random.randint(10, 22, size=(3, 4)))

    elif so_bai == 10:
        print("\n[Bai 10] Ma tran 10x10 vien 1, trong 0")
        mang = np.ones((10, 10))
        mang[1:-1, 1:-1] = 0
        print(mang)

    elif so_bai == 11:
        print("\n[Bai 11] Duong cheo chinh la 1, 2, 3, 4, 5")
        print(np.diag([1, 2, 3, 4, 5]))

    elif so_bai == 12:
        print("\n[Bai 12] Tong theo cot cua mang 3x3x3")
        mang = np.random.randint(1, 10, size=(3, 3, 3))
        print("Tong (axis 0):\n", mang.sum(axis=0))

    elif so_bai == 13:
        print("\n[Bai 13] Tich vo huong 2 vector")
        v1, v2 = np.random.rand(10), np.random.rand(10)
        print("Dot product:", np.dot(v1, v2))

    elif so_bai == 14:
        print("\n[Bai 14] Cong vector vao tung dong ma tran")
        M = np.random.rand(4, 3)
        v = np.random.rand(3)
        print("Ket qua:\n", M + v)

    elif so_bai == 15:
        print("\n[Bai 15] Phep cong tren 2 Series")
        ds1 = pd.Series([2, 4, 6, 8, 10])
        ds2 = pd.Series([1, 3, 5, 7, 10])
        print("Tong:\n", ds1 + ds2)

    elif so_bai == 16:
        print("\n[Bai 16] Trich xuat cot dau thanh Series")
        du_lieu = pd.DataFrame({'c1': [1, 4, 7], 'c2': [2, 5, 8], 'c3': [3, 6, 9]})
        print(du_lieu.iloc[:, 0])

    elif so_bai == 17:
        print("\n[Bai 17] Sap xep DataFrame theo cot A")
        du_lieu = pd.DataFrame(np.random.rand(4, 3), columns=['A', 'B', 'C'])
        print(du_lieu.sort_values(by='A'))

    elif so_bai == 18:
        print("\n[Bai 18] Thay doi thu tu index cua Series")
        ds = pd.Series([1, 2, 3], index=['A', 'B', 'C'])
        print(ds.reindex(['B', 'A', 'C']))

    elif so_bai == 19:
        print("\n[Bai 19] Tim phan tu co trong s1 nhung khong co trong s2")
        s1, s2 = pd.Series([1, 2, 3, 4, 5]), pd.Series([2, 4, 6, 8])
        print(s1[~s1.isin(s2)])

    elif so_bai == 20:
        print("\n[Bai 20] Tim tap hop Hoi va Giao")
        m1 = np.random.randint(0, 10, 20)
        m2 = np.random.randint(0, 10, 20)
        print("Hoi (Union):", np.union1d(m1, m2))
        print("Giao (Intersect):", np.intersect1d(m1, m2))

    elif so_bai == 21:
        print("\n[Bai 21] Noi Series theo chieu doc va ngang")
        s_a, s_b = pd.Series([0, 1, 2]), pd.Series(['p', 'q', 'r'])
        print("Noi doc:\n", pd.concat([s_a, s_b], axis=0))
        print("Noi ngang:\n", pd.concat([s_a, s_b], axis=1))

    # Du lieu mau cho bai 22-30
    data_mau = {
        'ten': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'diem': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'lan_thi': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'dat': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
    }
    chi_muc = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
    bang = pd.DataFrame(data_mau, index=chi_muc)

    if so_bai == 22: print(bang)
    elif so_bai == 23: print(bang.head(3))
    elif so_bai == 24: print(bang[['ten', 'diem']])
    elif so_bai == 25: print(bang[bang['lan_thi'] > 2])
    elif so_bai == 26: print(f"Dong: {bang.shape[0]}, Cot: {bang.shape[1]}")
    elif so_bai == 27: print(bang[bang['diem'].isnull()])
    elif so_bai == 28: print(bang[bang['diem'].between(15, 20)])
    elif so_bai == 29: print(bang[(bang['lan_thi'] > 2) & (bang['diem'].between(15, 20))])
    elif so_bai == 30:
        bang.loc['d', 'diem'] = 19
        print(bang.loc[['d']])

while True:
    try:
        lua_chon = input("\nNhap so bai (1-30) hoac 'q' de thoat: ")
        if lua_chon.lower() == 'q':
            break

        n = int(lua_chon)
        if 1 <= n <= 30:
            thuc_thi_bai_tap(n)
        else:
            print("Vui long chon trong khoang 1 den 30.")
    except ValueError:
        print("Loi: Hay nhap vao mot so nguyen!")

#==================================TENSORFLOW=================================

import tensorflow as tf
import numpy as np
rank_0_tensor=tf.constant(4)
print(rank_0_tensor)

rank_0_tensor=tf.constant(4)
print(rank_0_tensor)
r1=tf.constant(9,tf.int16)
print(r1)
r1_float=tf.constant(11.12,tf.float32)
print(r1_float)
r1_string=tf.constant('Hello world',tf.string)
print(r1_string)

import tensorflow as tf
rank_1_tensor=tf.constant([2.0,3.0,4.0])
print(rank_1_tensor)

import tensorflow as tf
rank_2_tensor=tf.constant([[1,2],[3,4],[5,6]],dtype=tf.float16)
print(rank_2_tensor)

import tensorflow as tf
import numpy as np
rank_3_tensor=tf.constant([[[0,1,2,3,4],[5,6,7,8,9]],[[10,11,12,13,14],[15,16,17,18,19]],[[20,21,22,23,24],[25,26,27,28,29]],])
print(rank_3_tensor)

import tensorflow as tf
import numpy as np
rank_3_tensor=tf.constant([[[0,1,2,3,4],[5,6,7,8,9]],[[10,11,12,13,14],[15,16,17,18,19]],[[20,21,22,23,24],[25,26,27,28,29]],])
print(rank_3_tensor)
print('shape:',rank_3_tensor.shape)
print('type of tensor:',rank_3_tensor.dtype)

t_zero=tf.zeros(10)
print(t_zero)

t_2_zero=tf.zeros([3,3])
print(t_2_zero)

t_3_zero=tf.zeros([3,3,5])
print(t_3_zero)

t_one=tf.ones(10)
print(t_one)

t_2_one=tf.ones([3,3])
print(t_2_one)

t_1=tf.fill(3,10)
print(t_1)

t_2=tf.fill([3,3],9)
print(t_2)

lin_tensor=tf.linspace(5.0,20.0,5)
print(lin_tensor)

#===================TIEN XU LY DU LIEU========================

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

def load_data():
    url = 'https://raw.githubusercontent.com/huynhhoc/DataAnalystDeepLearning/refs/heads/main/Data/babies.csv'
    return pd.read_csv(url, sep='\s+')

df = load_data()

# --- 1. XỬ LÝ DỮ LIỆU THIẾU (MISSING DATA) ---
# Trong bộ dữ liệu này, đôi khi giá trị thiếu được ký hiệu là số 999 hoặc 99
# Ta cần đưa chúng về dạng NaN để xử lý thống nhất
df.replace([999, 99], np.nan, inplace=True)

# Cách A: Xóa các dòng có bất kỳ ô nào trống (Đúng yêu cầu "đầy đủ dữ liệu" của bạn)
df_clean = df.dropna()

print(f"Kích thước ban đầu: {df.shape}")
print(f"Kích thước sau khi xóa dữ liệu thiếu: {df_clean.shape}")

# --- 2. XỬ LÝ OUTLIER (GIÁ TRỊ NGOẠI LAI) ---

Q1 = df_clean['bwt'].quantile(0.25)
Q3 = df_clean['bwt'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Lọc bỏ các giá trị nằm ngoài khoảng này
df_final = df_clean[(df_clean['bwt'] >= lower_bound) & (df_clean['bwt'] <= upper_bound)]

print(f"Kích thước sau khi loại Outliers: {df_final.shape}")

# --- 3. TRỰC QUAN HÓA ĐỂ KIỂM TRA ---
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
sns.boxplot(y=df_clean['bwt'])
plt.title('Trước khi xử lý Outlier')

plt.subplot(1, 2, 2)
sns.boxplot(y=df_final['bwt'])
plt.title('Sau khi xử lý Outlier')

plt.show()